# Generated by Django 4.2.7 on 2023-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_borrowed_by_bookloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloan',
            name='actual_borrowed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата взятия книги в библиотеке'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='borrowed_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата резервирования'),
        ),
    ]
